// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_web_api_key']}',
    appId: '1:582908932205:web:65713526016bf9fc4e4f64',
    messagingSenderId: '582908932205',
    projectId: 'push-notification-androi-103eb',
    authDomain: 'push-notification-androi-103eb.firebaseapp.com',
    storageBucket: 'push-notification-androi-103eb.firebasestorage.app',
    measurementId: 'G-RFT6DVWN4K',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_android_api_key']}',
    appId: '1:582908932205:android:613fc145cc86595e4e4f64',
    messagingSenderId: '582908932205',
    projectId: 'push-notification-androi-103eb',
    storageBucket: 'push-notification-androi-103eb.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['Firebase_ios_api_key']}',
    appId: '1:582908932205:ios:e85b77fcf30aa73f4e4f64',
    messagingSenderId: '582908932205',
    projectId: 'push-notification-androi-103eb',
    storageBucket: 'push-notification-androi-103eb.firebasestorage.app',
    iosBundleId: 'com.notification.andoird.ios.notificationServicesAndroidIos',
  );
}
